### PR TITLE
Gaussian blur & bug fixes for Fire/Ice Wyvern theme.

### PR DESCRIPTION
**Pull request by jelle619**
Note: Gaussian blur is only supported on Safari (iOS/macOS) and Microsoft Edge. Transparency without this effect is used for other web browsers. More info can be found here: https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter

Bug fixes:
- Fixes inconsistencies between Fire Wyvern and Ice Wyvern
- Removal of the navigation bar's shadow
- Added colours to previously undefined elements which made them look out of place

### CODE REVIEW

**Comment by advaith1** [comment]
Looks like backdrop-filter works in chrome and  chromium-based browsers if the `Experimental Web Platform Features` flag is enabled, according to [CanIUse](https://caniuse.com/#search=backdrop-filter)

**Comment by jelle619** [comment]
It does indeed, but that isn’t enabled by default as far as I know, basically ruling out Chromium-based browsers. 

In order for the blur effect to be visible, I had to make some elements less opaque, but if I were to do that it would look a bit too see-through without blur. I did not want to risk breaking compatibility with some very popular browsers, so the code responsible for the blur and changing the colour to something more transparant only become active om Safari and Microsoft Edge - two browsers that are fully compatible with the backdrop-filter feature. This means that, even if you were to enable Experimental Web Platform Feautures on Chrome, it still would not work.

**Comment by jelle619** [comment]
@advaith1 I have now updated the code so that it will now in fact support Chrome (and other Chromium-based web browsers) when these experimental features have been enabled. :D

(I have also added some slick promo material. Lmao)

**Comment by EndenDragon** [comment]
Merged in https://github.com/TitanEmbeds/Titan/commit/65e29b9debc15265409963bed162fa775c376b50

**Pull request closed without merging**
