### PR TITLE
Added new theme - RainbowUnicorn

### PR DESCRIPTION
**Pull request by oldaccount123434**
didnt have time to implement it into theme bar changer

### CODE REVIEW

**Comment by jelle619** [comment]
:thinking:

**Comment by circl-lastname** [comment]
🤔

**Comment by oldaccount123434** [comment]
🤔

**Comment by jelle619** [comment]
🤔

**Comment by oldaccount123434** [comment]
Just memed this convo.

**Comment by maxchoid** [comment]
@jtagt - close this PR request as it is old and I have done an update at #115 with more themes and features.

Thanks!

**Pull request closed without merging**
