### PR TITLE
Updated .gitignore to make life easier for me :'-) & added noscript compatibility + warning to site

### PR DESCRIPTION
**Pull request by jelle619**

### CODE REVIEW

**Comment by jelle619** [comment]
Plz check, this code is ruff. cannot test this code in my current situation. :-S

**Comment by ghost** [comment]
What I would do is make Titan redirect to the no script page to make it more consistent across titan

**Comment by MAX0342** [comment]
Or use the same technique in the embed instead of redirecting

**Comment by ghost** [comment]
@MAX0342 Or use the same technique in the embed instead of redirecting

**Comment by jelle619** [comment]
@MAX0342 but here's the thing... the Titan website works just fine on browsers with JavaScript disabled (with the exception of one button). I think that, and this is just my opinion, instead of disabling the complete website, we should only remove the links to pages that require JavaScript & some very slight modifications to the site. This way, users with JavaScript disabled can at least get to know what Titan's all about.

The reason why the embed uses a redirect, is because the complete embed itself becomes unusable without Javascript. This is not the case with the site. That's why I have decided not to use the redirect.

Besides that, in general, a redirect is not as reliable as something that's displayed on the same page. And with less reliable, I mean that some versions of IE disable redirects for 'security reasons'.

**Comment by ghost** [comment]
@jelle619 there's no need to write an essay

**Comment by ghost** [comment]
@jelle619 but that makes sense

**Comment by jelle619** [comment]
@MAX0342 there's a different between an essay and carefully explaining stuff. ;-)

**Comment by ghost** [comment]
I would love to test it but I can't

**Pull request closed without merging**
