### PR TITLE
German translation overhaul

### PR DESCRIPTION
**Pull request by SoftCreatR**

### CODE REVIEW

**Comment by acobeppp** [comment]
You can do it at our crowdin project

**Comment by SoftCreatR** [comment]
Done ;)

**Comment by acobeppp** [comment]
Now wait until it's aproved

**Comment by SoftCreatR** [comment]
That's what I do 😂

**Comment by acobeppp** [comment]
You don't approve
They do it

**Comment by SoftCreatR** [comment]
I know. I meant "now wait".

**Comment by popey456963** [comment]
I was always under the impression it was mostly handled by the website and that you didn't need to make a pull request.  Most of our translators probably don't know how to use Git.

Maybe completely wrong, but is this what [the webpage](http://translate.titanembeds.com/) told you to do?

**Comment by SoftCreatR** [comment]
It's all good. I just missed the Crowdin thing, that's why i've created the PR. As soon as @acobeppp told me to provide my translations there, i've closed the PR.

**Comment by EndenDragon** [comment]
@SoftCreatR Thanks for the PR! I was just gonna debate weather I should import your translations here in git to crowdin... but you've got it! I will now process the translations on crowdin and implement the new translations. :)

**Comment by SoftCreatR** [comment]
The translations at Crowdin are more complete. Just noticed that i missed some phrases, when translating them again :D

**Comment by EndenDragon** [comment]
@SoftCreatR German has been updated and pushed to live! 🎉 
Commit https://github.com/TitanEmbeds/Titan/commit/24120f4981058a6f5a7a57e3b3fa6531b7392028

**Comment by SoftCreatR** [comment]
@EndenDragon 

Just noticed, that you've accepted the new phrases, but it seems that you didn't notice, that i've also updated most of the existing translations, too :)

**Comment by EndenDragon** [comment]
@SoftCreatR Ooh, what do you mean by when you updated most of the existing translations?

**Comment by SoftCreatR** [comment]
I made suggestions to most of the existing translations.

**Comment by EndenDragon** [comment]
In the German language?

**Comment by SoftCreatR** [comment]
Yes :P 

Example:

image

**Comment by EndenDragon** [comment]
Whoops my bad
I did not see that before. Will update now!

**Comment by EndenDragon** [comment]
Approved and pushed them out to live! https://github.com/TitanEmbeds/Titan/commit/8acd6fb5acce81923ef50c0a57194a93f18cba49
You see, once the translation is approved in CrowdIn, apparently it doesn't show up in the proofreading mode when new suggestions are made. 😞

**Comment by SoftCreatR** [comment]
That's why i prefer Git :P 

However, seems to work now. Ty.

**Pull request closed without merging**
